// Character arcs: overall arc, main conflict, resolution. Three to four lines each.
// Planet geography: terrain, climate, what it is like to stand there.
window.SW_ARCS = {
  luke: "A farm boy who wanted off Tatooine becomes the last Jedi and the Rebellion's best pilot. His conflict is his father: he refuses to kill Vader and nearly dies for it. Anakin turns and saves him. Years later Luke fails Ben Solo, hides on Ahch-To, and redeems himself by facing Kylo as a projection so the Resistance can escape.",
  obiwan: "Padawan to Qui-Gon, master to Anakin, and the man who has to cut his brother down on Mustafar. His conflict is loyalty against duty. He loses Anakin, then spends nineteen years guarding Luke on Tatooine and lets Vader kill him so Luke can escape the Death Star.",
  yoda: "Grand Master of the Jedi for centuries, he presides over the Order's slow blindness to the Sith. His conflict is with his own certainty. He loses to Sidious, goes into exile on Dagobah, trains Luke, and dies telling him there is another Skywalker.",
  quigon: "A maverick Jedi who follows the living Force over the Council. His conflict is with the Order's rigidity: he insists Anakin is the Chosen One. Maul kills him on Naboo, and his last words bind Obi-Wan to train the boy. He returns as a Force ghost to guide Obi-Wan and Yoda.",
  mace: "Senior Jedi Master and the Council's hardest line. His conflict is that the war forces him to act as a general. He unmasks Palpatine and nearly kills him, but Anakin intervenes and Mace falls from the window.",
  ahsoka: "Anakin's padawan, framed for a bombing and cleared, walks away from the Jedi. Her conflict is whether to trust institutions at all. She survives Order 66, fights the Empire as Fulcrum, faces Vader on Malachor, and in her own series finally makes peace with her master's shadow and stays in Peridea to bring Ezra home.",
  kanan: "Caleb Dume, padawan who survived Order 66 by running, becomes Kanan Jarrus and hides from the Force. His conflict is fear of leading. He trains Ezra, is knighted by a Temple guard, loses his sight to Maul, and dies holding back a fuel explosion so Hera and the crew can live.",
  ezra: "A Lothal street kid with a Force gift joins the Ghost crew. His conflict is the temptation of quick power: the Sith holocron, Maul, the World Between Worlds. He chooses Lothal over himself and vanishes with Thrawn into deep space, to be found by Ahsoka years later.",
  cal: "A padawan hiding as a scrapper on Bracca, found by the Inquisitors. His conflict is his own guilt over Order 66 and whether the Jedi should continue. He recovers the holocron and destroys it to protect the children, then years later loses his crew's trust to a friend's betrayal and lets the dark side in to survive.",
  cere: "Former Jedi who was tortured into betraying her padawan Trilla. Her conflict is atonement. She takes Cal on, reconnects with the Force, and dies holding off Vader in the Jedi archive on Jedha.",
  rey: "A scavenger on Jakku who is nobody, then Palpatine's granddaughter, then a Skywalker by choice. Her conflict is fear of her blood. She refuses the Sith throne, kills Palpatine with the strength of all the Jedi, and takes the Skywalker name on Tatooine.",
  plo: "Kel Dor Jedi Master who found Ahsoka as a child. His conflict is the war's cost to his men. He is shot down by his own clones over Cato Neimoidia during Order 66.",
  depa: "Mace Windu's padawan, later a Master, who lost herself in a jungle war and recovered. Her conflict is guilt. She takes Caleb Dume as a padawan and dies on Kaller shielding him from Order 66.",
  quinlan: "A Kiffar Jedi with psychometry who works undercover among criminals. His conflict is the pull of the dark side. Sent to assassinate Dooku with Ventress, he falls, is redeemed by her sacrifice, and survives the Purge.",
  aayla: "Twi'lek Jedi Knight and Quinlan Vos's former padawan. Her conflict is proving herself outside his shadow. She is killed by her clones on Felucia in Order 66.",
  avar: "Marshal of Starlight Beacon and the Jedi who hears the Force as a song. Her conflict is Marchion Ro and her own need for vengeance after Starlight falls. She steps back from the edge and leads the Jedi against the Nihil.",
  elzar: "A gifted, restless Jedi and Avar Kriss's closest friend. His conflict is his own touch of the dark side under pressure. He seeks Yoda's counsel and finds his footing.",
  keeve: "Newly knighted Jedi at Starlight Beacon under Master Sskeer. Her conflict is a master who is losing his connection to the Force. She holds the line against the Drengir and the Nihil.",
  vernestra: "Youngest Jedi Knight of her age in the High Republic, later a Master a century on. Her conflict is a former padawan who became a Sith. She lies to the Council to protect the Order and goes to Yoda.",
  sol: "Jedi Master who took Osha as a padawan after the fire on Brendok. His conflict is the lie about what happened that night. He confesses too late and Osha kills him.",
  osha: "A former padawan who left the Order, twin to Mae. Her conflict is which twin is really the killer. She learns the truth about Brendok, kills Sol, and leaves with the Stranger.",
  revan: "Jedi Knight who defied the Council to win the Mandalorian Wars, fell, became a Sith Lord, and was mind-wiped into a Republic soldier. His conflict is his own past. He defeats Malak, then vanishes hunting the true Sith and is imprisoned by the Emperor for centuries.",
  bastila: "Jedi with rare battle meditation who captured Revan and shared a bond with him. Her conflict is that bond pulling her toward Malak. She falls, is redeemed, and marries Revan.",
  meetra: "The Jedi Exile, cut off from the Force after Malachor V. Her conflict is Kreia, who teaches her and betrays her. She defeats the Sith Triumvirate and follows Revan into the Unknown Regions.",
  satele: "Grand Master of the Jedi during the Cold War with the Sith Empire, descendant of Revan. Her conflict is a war she cannot win by force. She rebuilds the Order on Tython.",
  ulic: "Jedi Knight who infiltrated the Krath and fell to the dark side. His conflict is Exar Kun's war. He is stripped of the Force by his brother's death and dies in exile.",
  nomi: "Widow who became one of the great Jedi of her era. Her conflict is Ulic Qel-Droma, the man she loves and has to stop. She strips him of the Force.",
  zayne: "A hapless padawan framed for the murder of his classmates. His conflict is a Jedi Covenant that would rather kill him than admit its own crime. He clears his name.",
  cade: "Luke's descendant, a bounty hunter who has abandoned the Jedi. His conflict is Darth Krayt's Empire and his own reluctance. He kills Krayt and refuses the throne.",
  kyle: "Imperial officer turned mercenary, then Jedi. His conflict is his own capacity for the dark side. He gives up the Force, takes it back to stop Desann, and trains at Luke's academy.",
  kota: "A Jedi General who refused clone troops and survived Order 66. His conflict is despair after being blinded by Starkiller. Starkiller's turn gives him back a war worth fighting.",
  dagan: "High Republic Jedi who fell trying to keep Tanalorr. His conflict is the Order's abandonment of his frontier. Cal kills him.",
  loden: "Twi'lek Jedi Master, Bell Zettifar's teacher. His conflict is the Nihil, who capture him. He dies after months in Marchion Ro's hands.",
  jocasta: "Chief librarian of the Jedi Archives. Her conflict is the loss of everything she guarded. Vader kills her after she saves a list of Force-sensitive children.",
  anakin: "The slave boy who became the Chosen One, then Darth Vader. His conflict is fear: of losing his mother, then Padmé, then everything. He destroys the Jedi to save his wife and loses her anyway. Twenty-three years later his son's refusal to kill him breaks Sidious's hold, and he dies as Anakin.",
  palpatine: "A Naboo senator who was secretly the Sith Lord Sidious. His conflict is with the Jedi and time itself. He engineers the Clone Wars, becomes Emperor, is thrown down the Death Star shaft by Vader, returns in a cloned body on Exegol and is destroyed by Rey.",
  maul: "Sidious's first apprentice, cut in half by Obi-Wan on Naboo. His conflict is being discarded. He survives on hate, builds a criminal empire, loses his brother and Mandalore, and dies in Obi-Wan's arms on Tatooine asking about the Chosen One.",
  dooku: "Jedi Master who left the Order in disgust and became Darth Tyranus. His conflict is idealism curdled into cynicism. He leads the Separatists, and Sidious lets Anakin behead him.",
  savage: "Ventress's Nightbrother weapon, then Maul's brother and apprentice. His conflict is being used by everyone. Sidious kills him on Mandalore.",
  plagueis: "Muun Sith Lord who studied how to cheat death. His conflict is his apprentice. Palpatine murders him in his sleep the night before the Naboo vote.",
  bane: "The miner Dessel, who joined the Sith and destroyed them to rebuild them as two. His conflict is a Brotherhood that has forgotten what the Sith are. He survives the thought bomb on Ruusan and founds the Rule of Two.",
  malak: "Revan's friend and fellow Jedi, then his Sith apprentice, then his betrayer. His conflict is Revan. The amnesiac Revan kills him on the Star Forge.",
  kreia: "A former Jedi Master, then Sith Lord, who takes the Exile as a student. Her conflict is with the Force itself. She dies at Malachor after teaching the Exile everything and betraying her.",
  nihilus: "A wound in the Force who consumes whole worlds. His conflict is hunger. Meetra Surik kills him aboard the Ravager.",
  malgus: "Sith Lord who led the Sacking of Coruscant. His conflict is the Sith Empire's own decadence. He declares his own empire and falls.",
  exarkun: "A Jedi student who dug up Sith secrets and became the Dark Lord. His conflict is with the Jedi who trained him. His spirit is bound to Yavin 4 for four thousand years.",
  krayt: "A'Sharad Hett, Jedi turned Sith, ruler of a new Sith Empire a century after Endor. His conflict is Cade Skywalker. Cade kills him for good.",
  qimir: "The Stranger, a former padawan who became a Sith acolyte. His conflict is a Jedi Order that would not let him be free. He takes Osha as his student.",
  mae: "Osha's twin, raised to believe the Jedi killed their coven. Her conflict is vengeance against four Jedi. She learns the truth and is memory-wiped by Vernestra.",
  starkiller: "Galen Marek, raised as Vader's secret apprentice. His conflict is his master's betrayal. He turns, saves the founders of the Rebellion, and dies fighting the Emperor.",
  padme: "Queen of Naboo at fourteen, then senator, secretly Anakin's wife. Her conflict is the Republic she serves collapsing while her husband turns. She dies on Polis Massa after giving birth, believing there is still good in him.",
  bail: "Senator from Alderaan and one of the Rebellion's founders. His conflict is opposing Palpatine from inside a dying Senate. He adopts Leia and dies with Alderaan.",
  jarjar: "A clumsy Gungan exile who became a senator. His conflict is being useful. He proposes the emergency powers that hand Palpatine the Republic.",
  rex: "Clone Captain of the 501st, Anakin's right hand. His conflict is orders he cannot follow. He removes his inhibitor chip, survives Order 66 with Ahsoka, and fights at Endor.",
  cody: "Commander of the 212th under Obi-Wan. His conflict is loyalty overridden by a chip. He orders the shot on Utapau and later deserts the Empire.",
  hunter: "Leader of Clone Force 99 and Omega's guardian. His conflict is keeping his family out of a war that keeps finding them. He retires to Pabu.",
  wrecker: "The Bad Batch's strongman. His conflict is the chip in his head. He recovers and stays with the family.",
  tech: "The Bad Batch's analyst. His conflict is a mind that never stops calculating. He sacrifices himself on Eriadu so the others can escape.",
  crosshair: "The Bad Batch's sniper, loyal to the Empire longer than the rest. His conflict is choosing sides. He returns to his brothers.",
  omega: "A young unaltered clone with Jango's blood, hunted by the Empire. Her conflict is being an experiment. She frees the other children from Tantiss and grows up to fly for the Rebellion.",
  echo: "A clone thought dead, rebuilt by the Techno Union. His conflict is being part machine. He joins Rex's clone underground.",
  carth: "Republic pilot who lost his family to Malak. His conflict is trust after betrayal. He helps Revan defeat Malak.",
  nute: "Viceroy of the Trade Federation who blockaded Naboo. His conflict is cowardice. Vader kills him on Mustafar.",
  grievous: "A Kaleesh warlord rebuilt as a cyborg general for the Separatists. His conflict is the Jedi he collects lightsabers from. Obi-Wan kills him on Utapau.",
  ventress: "Dooku's assassin, then a Nightsister, then a bounty hunter. Her conflict is Dooku's betrayal. She saves Quinlan Vos and dies for it.",
  tarkin: "Governor turned Grand Moff, the Empire's most ruthless administrator. His conflict is proving fear works. He destroys Alderaan and dies with the Death Star.",
  thrawn: "Chiss exile who rose to Grand Admiral by seeing what art reveals about people. His conflict is Ezra Bridger. Ezra's purrgil drag him to another galaxy; Morgan Elsbeth brings him back.",
  krennic: "Director of the Death Star project. His conflict is credit, and Tarkin taking it. He dies on Scarif under his own station's fire.",
  grandinquisitor: "A Pau'an Jedi Temple guard who fell after Ahsoka's trial. His conflict is Kanan Jarrus. He chooses to fall into the reactor rather than face Vader's disappointment.",
  reva: "Third Sister, a youngling who survived Order 66 and joined the Inquisitors to get close to Vader. Her conflict is vengeance. She cannot kill Luke and lets go.",
  trilla: "Cere Junda's padawan, broken into the Second Sister. Her conflict is her former master. Cere reaches her, and Vader kills her.",
  gideon: "Imperial Moff who wants Grogu's blood and the Darksaber. His conflict is Din Djarin. He dies in his own base on Mandalore.",
  pryce: "Lothal's Imperial governor, who sold her world for a title. Her conflict is Hera Syndulla. She dies in the Dome she refused to abandon.",
  sloane: "Imperial admiral trying to hold the Empire together after Endor. Her conflict is Gallius Rax. She vanishes into the Unknown Regions.",
  iden: "Inferno Squad commander. Her conflict is Operation: Cinder against her own homeworld. She defects and fights for the New Republic.",
  delmeeko: "Inferno Squad soldier, later Iden's husband. His conflict is a friend who stayed loyal. Hask kills him.",
  hask: "Inferno Squad soldier who stays with the Empire. His conflict is Iden's defection. Iden kills him.",
  dedra: "ISB supervisor who hunts Axis. Her conflict is the one competent person in a bureaucracy of careerists. Her success makes her a threat and she ends in Narkina 5.",
  syril: "A corporate inspector obsessed with catching Cassian. His conflict is wanting to matter. He dies in the Ghorman massacre realising what he served.",
  kallus: "ISB agent hunting the Ghost crew. His conflict is Zeb, who saves his life. He becomes the Rebel spy Fulcrum.",
  eli: "A supply officer from Wild Space who became Thrawn's aide. His conflict is loyalty across two empires. He joins the Chiss Ascendancy.",
  galen: "Brilliant scientist forced to build the Death Star. His conflict is complicity. He builds the flaw in and sends Bodhi with the message.",
  morgan: "Nightsister survivor who built Thrawn's Imperial navy. Her conflict is bringing Thrawn back. She gives her life on Peridea.",
  barriss: "Mirialan padawan who bombed the Temple and framed Ahsoka. Her conflict is the Jedi's role in the war. She becomes an Inquisitor and then walks away.",
  jorus: "Insane Dark Jedi clone recruited by Thrawn. His conflict is his own madness. He dies at Mount Tantiss.",
  xizor: "Falleen prince who ran Black Sun. His conflict is Vader. Vader destroys his skyhook.",
  leia: "Princess, senator, Rebel leader, general. Her conflict is a war that costs her everything: her planet, her father's truth, her son. She dies reaching out to Ben across the galaxy and brings him back.",
  han: "Corellian smuggler who only wanted to get paid. His conflict is caring. He comes back at Yavin, is frozen for Leia, and dies on Starkiller Base trying to bring his son home.",
  chewbacca: "Wookiee warrior, Han's co-pilot, loyal through everything. His conflict is losing the people he protects. He outlives Han and carries on.",
  lando: "Gambler who ran Cloud City and sold Han out. His conflict is the cost of the deal. He blows up the second Death Star and comes back at Exegol.",
  hera: "Twi'lek pilot who leads the Ghost crew. Her conflict is Lothal against the whole galaxy. She loses Kanan, raises their son, and becomes a general.",
  zeb: "Last of the Lasat honour guard. His conflict is Kallus, who helped destroy his people. He leads his people to Lira San.",
  jyn: "Galen Erso's daughter, abandoned twice. Her conflict is whether to fight at all. She steals the Death Star plans and dies on Scarif.",
  cassian: "A thief and killer from Kenari who becomes the Rebellion's spy. His conflict is what he is willing to become. He dies on Scarif having sent the plans.",
  chirrut: "Blind Guardian of the Whills. His conflict is faith without the Force. He walks through the fire on Scarif.",
  baze: "Former Guardian who lost his faith. His conflict is Chirrut's. He follows him into death.",
  bodhi: "Imperial cargo pilot who defected with Galen's message. His conflict is believing anyone will listen. He gets the transmission out.",
  saw: "Onderon rebel, later an extremist. His conflict is a Rebellion that will not go far enough. He dies on Jedha.",
  monmothma: "Senator who founded the Rebel Alliance. Her conflict is funding a war under Palpatine's nose. She becomes Chancellor of the New Republic.",
  luthen: "Antique dealer and spymaster. His conflict is that he has burned his own decency for a dawn he will not see. He dies to protect the Rebellion.",
  bix: "Ferrix mechanic and Cassian's friend. Her conflict is Imperial torture. She joins the Rebellion.",
  wedge: "Corellian pilot who survived both Death Star runs. His conflict is outliving everyone. He founds Rogue Squadron.",
  norra: "Rebel pilot hunting Imperial remnants after Endor. Her conflict is a son she left behind. She helps end the war at Jakku.",
  juno: "Imperial pilot assigned to Starkiller. Her conflict is loyalty to him over the Empire. She becomes a Rebel captain.",
  thane: "Jelucan boy who joined the Imperial Academy with Ciena. His conflict is the Empire he came to hate. He defects to the Rebellion.",
  ciena: "Thane's best friend who stayed loyal to the Empire. Her conflict is honour against everything she sees. She is captured at Jakku.",
  marajade: "Emperor's Hand ordered to kill Luke Skywalker. Her conflict is that command in her head. She kills Luke's clone instead and later marries him.",
  kaz: "New Republic pilot spying for the Resistance. His conflict is being in over his head. He proves himself at the Colossus.",
  finn: "A stormtrooper who refused to fire. His conflict is running from the First Order. He stops running and becomes a Resistance general.",
  poe: "Best pilot in the Resistance. His conflict is a hot head. He learns to lead.",
  rose: "Maintenance worker whose sister died a hero. Her conflict is Canto Bight's glamour. She saves Finn on Crait.",
  kylo: "Ben Solo, Han and Leia's son, trained by Luke and turned by Snoke. His conflict is the pull to the light. He kills his father, then Snoke, then is turned back by his mother and Rey and gives his life for her.",
  snoke: "Supreme Leader of the First Order, a creation of Palpatine's. His conflict is Kylo's wavering. Kylo cuts him in half.",
  hux: "General of the First Order, a fanatic. His conflict is Kylo Ren. He becomes the Resistance's spy out of spite and is shot for it.",
  phasma: "Captain of the stormtroopers, chrome and ruthless. Her conflict is Finn. She falls in the fire of the Supremacy.",
  din: "A Mandalorian foundling and bounty hunter. His conflict is a creed against a child. He gives Grogu up, gets him back, and retakes Mandalore.",
  grogu: "A fifty-year-old Force-sensitive child who survived the Purge. His conflict is choosing between Luke and Din. He chooses Din.",
  bokatan: "Death Watch lieutenant, Satine's sister, later leader of Mandalore. Her conflict is a throne she keeps losing. She leads the retaking of Mandalore.",
  satine: "Pacifist Duchess of Mandalore. Her conflict is Death Watch and Maul. Maul kills her in front of Obi-Wan.",
  sabine: "Mandalorian artist and weapons designer, Ezra's friend. Her conflict is a Force she cannot feel. She opens herself to it to find him.",
  armorer: "Keeper of the Children of the Watch. Her conflict is a creed that keeps her people apart. She reforges Mandalore.",
  canderous: "Mandalorian mercenary who fought Revan and then followed him. His conflict is a people without a leader. He becomes Mandalore.",
  jango: "Bounty hunter and template for the clone army. His conflict is the Jedi. Mace beheads him on Geonosis.",
  boba: "Jango's clone son, the galaxy's most feared bounty hunter. His conflict is survival after the Sarlacc. He takes Jabba's throne.",
  jabba: "Crime lord of Tatooine. His conflict is Han's debt. Leia strangles him.",
  cadbane: "Duros bounty hunter, the best of the Clone Wars. His conflict is Boba Fett. Boba kills him on Tatooine.",
  hondo: "Weequay pirate and occasional ally. His conflict is profit. He survives everything.",
  fennec: "Elite assassin left for dead on Tatooine. Her conflict is a debt to Boba. She becomes his partner.",
  greef: "Bounty Hunters' Guild agent on Nevarro. His conflict is the Imperial remnant. He becomes Nevarro's magistrate.",
  qira: "Han's first love, bound to Crimson Dawn. Her conflict is Han against Maul. She chooses Crimson Dawn.",
  beckett: "Career thief who took Han on. His conflict is trust. Han shoots him first.",
  dryden: "Crimson Dawn's public face. His conflict is Beckett's failure. Qi'ra kills him.",
  aphra: "Rogue archaeologist who worked for Vader and lived. Her conflict is survival. She keeps finding worse trouble.",
  krrsantan: "Wookiee bounty hunter with gladiator scars. His conflict is whoever hired him last. He guards Boba's throne.",
  aurra: "Bounty hunter who trained Boba. Her conflict is the Jedi she hunts. Tobias Beckett kills her.",
  dash: "Corellian smuggler and Han's rival. His conflict is the Empire in Han's absence. He survives.",
  kay: "Cantonica thief with a merqaal named Nix. Her conflict is a heist gone wrong and a price on her head. She pulls off the bigger job.",
  karrde: "Smuggler chief with a reputation for information. His conflict is Thrawn. He helps the New Republic.",
  sana: "Smuggler who claimed to be Han's wife. Her conflict is Han and Leia. She works with the Rebellion.",
  jod: "A pirate who may once have been a Jedi. His conflict is At Attin's treasury. The kids beat him.",
  marchion: "Eye of the Nihil, who wanted a galaxy without Jedi. His conflict is Avar Kriss and the Order. He falls at the end of the High Republic.",
  enfys: "Leader of the Cloud-Riders, secretly a rebel. Her conflict is Crimson Dawn. She gets the coaxium.",
  maz: "Thousand-year-old pirate queen of Takodana. Her conflict is nothing she cannot outlast. She hands Rey the lightsaber.",
  shmi: "Anakin's mother, a slave on Tatooine. Her conflict is letting him go. Tusken Raiders kill her.",
  owen: "Anakin's stepbrother, Luke's uncle. His conflict is keeping Luke from his father's path. Stormtroopers kill him.",
  beru: "Owen's wife, Luke's aunt. Her conflict is a boy who needs to leave. She dies with Owen.",
  merrin: "Last Nightsister of Dathomir. Her conflict is the Jedi she blames. She joins Cal's crew.",
  greez: "Latero pilot of the Mantis. His conflict is a gambling debt. He opens a cantina on Koboh.",
  bode: "Jedi survivor and Imperial spy. His conflict is his daughter's safety. Cal kills him.",
  baylan: "Former Jedi turned mercenary. His conflict is a galaxy of endless cycles. He walks toward something on Peridea.",
  shin: "Baylan's apprentice. Her conflict is a master who leaves her. She stays with the bandits.",
  kuiil: "Ugnaught who paid off his indenture. His conflict is peace. He dies protecting the Child.",
  peli: "Mos Eisley mechanic. Her conflict is droids she does not trust. She builds Din's N-1.",
  wim: "At Attin kid who wanted an adventure. His conflict is getting one. He gets home.",
  fern: "At Attin kid and self-appointed captain. Her conflict is Wim. They get home.",
  kb: "Fern's friend with cybernetic implants. Her conflict is trusting Jod. They get home.",
  neel: "Wim's blue-skinned friend. His conflict is everything scary. He gets home.",
  cham: "Ryloth freedom fighter, Hera's father. His conflict is Vader. He survives the Empire.",
  maarva: "Cassian's adoptive mother on Ferrix. Her conflict is a town that will not fight. Her funeral starts the riot.",
  kino: "Narkina 5 floor manager. His conflict is a system he ran until he learned it lied. He cannot swim.",
  tala: "Imperial officer secretly helping the Path. Her conflict is Vader's Inquisitors. She dies buying time on Jabiim.",
  sabe: "Padmé's handmaiden and decoy. Her conflict is Padmé's death. She keeps looking for the truth.",
  c3po: "Protocol droid built by Anakin, fluent in six million forms. His conflict is fear. He is there for all of it.",
  r2d2: "Astromech who has carried more secrets than anyone. His conflict is C-3PO. He never stops.",
  bb8: "Poe's astromech with the map to Luke. His conflict is the desert. He finds Rey.",
  chopper: "Hera's cranky astromech from the Clone Wars. His conflict is everyone. He survives.",
  k2so: "Reprogrammed Imperial droid with no filter. His conflict is Cassian's caution. He dies on Scarif.",
  bd1: "Explorer droid holding the map to the holocron. His conflict is trust. He chooses Cal.",
  ig11: "Bounty droid rebuilt as a nurse. His conflict is his programming. He self-destructs for Grogu.",
  hk47: "Assassin droid built by Revan. His conflict is meatbags. He serves Revan again.",
  l337: "Lando's droid and a droid-rights activist. Her conflict is servitude. She becomes the Falcon's brain.",
  triplezero: "A protocol droid built for torture. His conflict is Aphra. He escapes her.",
  nd5: "Commando droid bound to Jaylen Vrax. His conflict is a restraining bolt. Kay frees him.",
  huyang: "Lightsaber-building droid who has trained Jedi for a thousand generations. His conflict is Sabine's stubbornness. He goes to Peridea.",
  sm33: "Ancient pirate droid on the Onyx Cinder. His conflict is a mutiny he barely remembers. He serves the kids.",
};

window.SW_GEO = {
  tatooine: "Two suns over rock and dune. The Jundland Wastes are canyon country, the Dune Sea is open sand, and the Great Pit of Carkoon sits in it. Days near fifty degrees, nights that freeze. Moisture farms draw water from the air.",
  coruscant: "One city, planet-wide, kilometres deep. The upper levels see sky and the Senate; the underlevels never see daylight. The Jedi Temple stands on a plateau over a Sith shrine.",
  naboo: "Rolling plains, waterfalls and the lake country around Varykino. Theed sits on cliffs above the falls. The Gungans live in Otoh Gunga, a bubble city under the lake. A porous core lets ships travel through the planet.",
  alderaan: "Snow-capped mountains, grasslands and quiet cities built into the terrain. Alderaan had no weapons and no ugly buildings. Now an asteroid field.",
  hoth: "Ice and snow from pole to pole, blizzards every night, temperatures that kill in minutes. Tauntauns, wampas and not much else.",
  dagobah: "Swamp under permanent fog, root systems the size of buildings, and a cave strong with the dark side. Yoda's hut sits in the mud.",
  bespin: "A gas giant with a habitable band in its upper atmosphere. Cloud City floats there on repulsors, mining tibanna gas, with pink skies at sunset.",
  endor: "Forest moon of giant trees and mist, home of the Ewoks. The second Death Star's shield generator sat in a clearing.",
  yavin4: "Jungle moon of a red gas giant, with Massassi stone temples rising out of the canopy. The Rebel base lived inside the Great Temple.",
  jakku: "Desert littered with the wrecks of the Battle of Jakku. Star Destroyers lie half-buried in the sand. Niima Outpost trades in scrap.",
  takodana: "Temperate forest and lakes. Maz Kanata's castle stood on the shore for a thousand years.",
  ahchto: "Cold grey ocean dotted with rocky islands. Stone huts, steps carved into the cliff, porgs, and the first Jedi temple.",
  crait: "White salt crust over blood-red mineral soil. Vulptex crystal foxes and an abandoned Rebel base.",
  exegol: "Lightning, black rock and a bottomless sky. The Sith Citadel and its throne stand above an arena of Sith cultists.",
  mustafar: "Lava rivers and black rock, a mining world. Vader's castle stands over the site of his fall.",
  kamino: "Endless ocean under constant storms. Tipoca City stands on stilts above the waves.",
  geonosis: "Red rock desert and spires, ringed. The Geonosians live in hives and build droids in foundries beneath the surface.",
  utapau: "A dry world with vast sinkholes. The cities are built into the sinkhole walls.",
  kashyyyk: "Wroshyr trees kilometres tall. The Wookiees live in the canopy; the shadowlands below are lethal.",
  mandalore: "Deserts of white sand and glass after the Purge, with domed cities. Beneath, the living waters of the Mines of Mandalore.",
  dathomir: "Red skies, red mist, dark forest and the Nightsisters' stone fortress. Rancors and the Nightbrothers' village.",
  lothal: "Golden grasslands, rock spires and small cities. Loth-cats, loth-wolves and an Imperial factory.",
  ryloth: "Tidally locked. One side scorched, one side frozen, and a twilight band where the Twi'leks live in caves.",
  jedha: "A cold desert moon. The Holy City was carved into a mesa. The Temple of the Kyber was its heart.",
  scarif: "Tropical islands, turquoise shallows and palm trees around the Imperial Citadel.",
  corellia: "Industrial world of shipyards, canals and grey weather. Coronet City.",
  kessel: "A barren world of spice mines and slave labour, ringed by the Maw's black holes.",
  nevarro: "Volcanic plains, black rock and lava rivers. One town, one cantina.",
  ferrix: "A dry, brown salvage world. Brick buildings, scrap yards and a town that hits an anvil to warn itself.",
  aldhani: "Highland valleys, cold rivers and stone. The Eye, a meteor shower, fills the sky once every three years.",
  narkina5: "An ocean world. The prison is a floating factory with electrified floors.",
  ghorman: "A temperate Core world of textile towns and a plaza that became a massacre.",
  peridea: "Grey, broken and old. A graveyard of purrgil bones, ruins of the Nightsisters, and a fortress.",
  seatos: "Green coasts and a stone henge that is really a star map.",
  brendok: "A forested world with a stone fortress and a bunta tree.",
  korriban: "Red desert valley lined with the tombs of the Dark Lords. The Valley of the Dark Lords.",
  taris: "An ecumenopolis, then rubble after Malak. Rakghoul-infested Undercity.",
  dantooine: "Grasslands, lavender blba trees and a Jedi enclave.",
  malachor: "A cracked, dead world. The Sith temple is a pyramid over a superweapon.",
  ossus: "Once green, scarred by the Cron supernova. Jedi library ruins.",
  dromundkaas: "Jungle under a permanent lightning storm. The Sith capital Kaas City.",
  tython: "Mountains and forest in the Deep Core, seat of the first Jedi.",
  hetzal: "Agricultural system of farms and moons, saved from hyperspace debris.",
  bracca: "One planetary scrapyard. Starships are cut apart in the rain.",
  bogano: "Mesas over green bog, giant creatures and an ancient vault.",
  zeffo: "Windswept cliffs, ice and tombs of an extinct Force-sensitive people.",
  koboh: "A frontier world of canyons, forests and abandoned High Republic outposts.",
  byss: "A Deep Core world of blue-green light where the reborn Emperor hid.",
  myrkr: "Forest where ysalamiri push back the Force.",
  ruusan: "Grassland and hills, site of seven battles.",
  serenno: "Aristocratic world of castles and estates, Dooku's home.",
  eriadu: "Industrial and polluted Outer Rim world, the Tarkin seat.",
  csilla: "Frozen Chiss capital with cities beneath the ice.",
  batuu: "Black spires of petrified trees around an old trading outpost.",
  hosnian: "New Republic capital of towers and plazas, destroyed by Starkiller Base.",
  chandrila: "Green, peaceful Core world of farms and Hanna City.",
  vardos: "A jewel of an Imperial loyalist world, burned by Cinder.",
  mimban: "Mud, trenches and constant rain. A Clone Wars battlefield the Empire never left.",
  vandor: "Snowy mountains with a conveyex line through the passes.",
  savareen: "Coastal refinery on a windswept shore.",
  cantonica: "Desert with an artificial sea and the casino city of Canto Bight.",
  kijimi: "Cold mountain city of narrow alleys.",
  pasaana: "Desert of the Aki-Aki and sinking fields.",
  kefbir: "Ocean moon where the second Death Star fell. Waves the size of buildings.",
  dqar: "Jungle world of the Resistance base.",
  shili: "Grasslands of red and white scrub, Togruta homeworld.",
  polismassa: "An asteroid with a medical outpost.",
  lahmu: "Black sand, green hills and volcanic soil. One farm.",
  onderon: "Jungle with the walled city Iziz and a moon full of beasts.",
  umbara: "A world of perpetual shadow, lit by bioluminescence.",
  mortis: "A realm that changes with the Force: light, then dark.",
  ilum: "Ice and kyber caves, later carved into Starkiller Base.",
  moncala: "Ocean world with cities on and beneath the sea.",
  narshaddaa: "The Smugglers' Moon, a neon city-moon of Nal Hutta.",
  felucia: "Fungal jungle in psychedelic colours.",
  akiva: "Humid jungle with an old Imperial palace.",
  jelucan: "Mountain valleys and old traditions.",
  atattin: "A hidden suburban world under a permanent cloud barrier.",
  toshara: "Savanna moon with a great wind and the city of Mirogana.",
  telos: "Rebuilt after orbital bombardment, with Citadel Station above.",
  manaan: "Ocean world with one city on stilts, Ahto City.",
  muunilinst: "Banking world of towers and vaults.",
  apatros: "A cortosis mining world of dust and poverty.",
  nur: "Ocean moon of Mustafar with Fortress Inquisitorius rising from the water.",
  wayland: "Forest world hiding Mount Tantiss.",
  starlight: "A Jedi space station with gardens and a lighthouse beam.",
  raxusprime: "A planet-wide junkyard of toxic sludge.",
  sorgan: "Forest and krill ponds.",
  arvala7: "Rocky desert with mudhorns.",
  jabiim: "Rain and mud without end.",
  daiyu: "Neon city of crime and street food.",
  ordmantell: "A rough trade world of scrap and cantinas.",
  pabu: "An island of terraced houses over a warm sea.",
  kaller: "Rocky world of cliffs and Clone Wars trenches.",
  haruunkal: "Jungle uplands where the Korunnai live.",
  vrogasvas: "A dead world with a Rebel refuelling base.",
  carnelion: "Ruined world where two factions fought in the wreckage of a war.",
  shutorun: "A world of ore and lava dukes.",
  hosnianx: "Ocean world with a refuelling platform, the Colossus.",
  nathema: "A dead world, its life drained by the Sith Emperor.",
  stewjon: "Little is recorded beyond green fields. Obi-Wan left it as an infant.",
  nalhutta: "A polluted swamp world of bogs and acid rain, the Hutt homeworld.",
  lasan: "Rocky highlands, once home to the Lasat before the Empire's disruptors emptied it.",
  krownest: "Snow, pine forest and Clan Wren's stronghold on a frozen lake.",
  kalevala: "A Mandalorian world of pale plains and domed cities, seat of House Kryze.",
  concorddawn: "Agricultural world with a shattered moon overhead.",
  duro: "An industrial world whose surface was polluted long ago; the Duros live in orbital cities.",
  arkanis: "Rain nearly every day, with an Imperial academy on the coast.",
  mirial: "A cold, dry world of the tattooed Mirialans.",
  socorro: "Black volcanic sand and smugglers' ports.",
  pijal: "A temperate world with a moon of miners and a royal court.",
  kenari: "Jungle world poisoned by an Imperial mining accident.",
  talravin: "A quiet Inner Rim world of towns and farmland.",
  ordo: "Harsh clan world of the Mandalorian Ordo.",
  falleen: "Humid tropical world with a black-water ocean.",
  vallt: "Frozen Outer Rim world where the Ersos were held.",
  kalee: "Jungle and grassland, ravaged by the Huk wars.",
  lexrul: "Temperate Core world of cities and universities.",
  chalacta: "A quiet world known for its contemplative traditions.",
  dorin: "Thin helium atmosphere; the Kel Dor wear masks off-world.",
  kiffu: "Rugged world with a moon, Kiffex, used as a prison.",
  sulon: "Farming moon of Sullust with Kyle Katarn's family homestead.",
  parnassos: "A harsh, ruined world of nuclear wastes and warring clans.",
  haysminor: "A mining world stripped by the First Order.",
  ganthel: "Outer Rim world of shipyards.",
  lysatra: "Wild Space farming world at the edge of the map.",
  grange: "Agricultural world where Galen Erso grew up.",
  sriluur: "Desert world of the Weequay, dry and windswept.",
  gleeanselm: "Water world of lagoons and swamps.",
  arbina: "Hardscrabble world Aphra left and never went back to.",
  aqvetina: "Farm world destroyed by Separatist droids in the Clone Wars.",
  mygeeto: "A frozen world of crystal spires and Muun banking vaults.",
};
