// Named places on each planet: the Wookieepedia article (for a still) and a
// Sketchfab search (for a community 3D model).
window.SW_SITES = {
  tatooine: [
    { name: "Mos Eisley cantina", wiki: "Chalmun%27s_Spaceport_Cantina", sfq: "star wars mos eisley cantina" },
    { name: "Jabba's Palace", wiki: "Jabba%27s_Palace", sfq: "star wars jabba palace star wars" },
    { name: "Lars homestead", wiki: "Lars_moisture_farm", sfq: "star wars lars homestead tatooine" },
    { name: "Mos Espa arena", wiki: "Mos_Espa_Grand_Arena", sfq: "star wars mos espa podrace arena" },
  ],
  coruscant: [
    { name: "Jedi Temple", wiki: "Jedi_Temple", sfq: "star wars jedi temple coruscant" },
    { name: "Senate Building", wiki: "Senate_Building", sfq: "star wars galactic senate building star wars" },
    { name: "Imperial Palace", wiki: "Imperial_Palace", sfq: "star wars imperial palace coruscant" },
  ],
  naboo: [
    { name: "Theed Royal Palace", wiki: "Theed_Royal_Palace", sfq: "star wars theed palace naboo" },
    { name: "Otoh Gunga", wiki: "Otoh_Gunga", sfq: "star wars otoh gunga" },
    { name: "Varykino", wiki: "Varykino", sfq: "star wars naboo lake retreat varykino" },
  ],
  hoth: [ { name: "Echo Base", wiki: "Echo_Base", sfq: "star wars echo base hoth" } ],
  bespin: [ { name: "Cloud City", wiki: "Cloud_City", sfq: "star wars cloud city bespin" } ],
  endor: [
    { name: "Bright Tree Village", wiki: "Bright_Tree_Village", sfq: "star wars ewok village endor" },
    { name: "Shield generator bunker", wiki: "Imperial_shield_generator_bunker", sfq: "star wars endor bunker star wars" },
  ],
  yavin4: [ { name: "Great Temple", wiki: "Great_Temple", sfq: "star wars yavin 4 great temple rebel base" } ],
  dagobah: [ { name: "Yoda's hut", wiki: "Yoda%27s_hut", sfq: "star wars yoda hut dagobah" } ],
  jakku: [
    { name: "Niima Outpost", wiki: "Niima_Outpost", sfq: "star wars niima outpost jakku" },
    { name: "Star Destroyer graveyard", wiki: "Graveyard_of_Giants", sfq: "star wars jakku star destroyer wreck" },
  ],
  takodana: [ { name: "Maz Kanata's castle", wiki: "Maz_Kanata%27s_castle", sfq: "star wars maz kanata castle" } ],
  ahchto: [ { name: "Temple Island", wiki: "Temple_Island", sfq: "star wars ahch-to island jedi temple" } ],
  crait: [ { name: "Crait outpost", wiki: "Crait_outpost", sfq: "star wars crait rebel base" } ],
  exegol: [ { name: "Sith Citadel", wiki: "Sith_Citadel", sfq: "star wars exegol sith citadel throne" } ],
  mustafar: [
    { name: "Fortress Vader", wiki: "Fortress_Vader", sfq: "star wars vader castle mustafar" },
    { name: "Mining complex", wiki: "Mustafar_mining_complex", sfq: "star wars mustafar mining facility" },
  ],
  kamino: [ { name: "Tipoca City", wiki: "Tipoca_City", sfq: "star wars tipoca city kamino" } ],
  geonosis: [ { name: "Petranaki arena", wiki: "Petranaki_Arena", sfq: "star wars geonosis arena star wars" } ],
  utapau: [ { name: "Pau City", wiki: "Pau_City", sfq: "star wars utapau sinkhole city" } ],
  kashyyyk: [ { name: "Kachirho", wiki: "Kachirho", sfq: "star wars kashyyyk wookiee tree city" } ],
  mandalore: [
    { name: "Sundari", wiki: "Sundari", sfq: "star wars sundari mandalore dome city" },
    { name: "Mines of Mandalore", wiki: "Mines_of_Mandalore", sfq: "star wars mines of mandalore living waters" },
  ],
  dathomir: [ { name: "Nightsister fortress", wiki: "Nightsister_fortress", sfq: "star wars dathomir nightsister fortress" } ],
  lothal: [
    { name: "Capital City dome", wiki: "Imperial_Complex_(Lothal)", sfq: "star wars lothal imperial dome" },
    { name: "Lothal Jedi Temple", wiki: "Lothal_Jedi_Temple", sfq: "star wars lothal jedi temple" },
  ],
  jedha: [
    { name: "Holy City", wiki: "Jedha_City", sfq: "star wars jedha holy city" },
    { name: "Temple of the Kyber", wiki: "Temple_of_the_Kyber", sfq: "star wars temple of the kyber jedha" },
  ],
  scarif: [ { name: "Citadel Tower", wiki: "Citadel_Tower", sfq: "star wars scarif citadel tower" } ],
  corellia: [ { name: "Coronet City", wiki: "Coronet_City", sfq: "star wars coronet city corellia" } ],
  kessel: [ { name: "Kessel spice mines", wiki: "Spice_mines_of_Kessel", sfq: "star wars kessel mine star wars" } ],
  nevarro: [ { name: "Nevarro City", wiki: "Nevarro_City", sfq: "star wars nevarro cantina mandalorian" } ],
  ferrix: [ { name: "Rix Road", wiki: "Rix_Road", sfq: "star wars ferrix andor town" } ],
  aldhani: [ { name: "Aldhani garrison", wiki: "Aldhani_Imperial_Garrison", sfq: "star wars aldhani garrison andor" } ],
  narkina5: [ { name: "Narkina 5 prison", wiki: "Narkina_5_Imperial_Prison_Complex", sfq: "star wars narkina 5 prison andor" } ],
  korriban: [ { name: "Valley of the Dark Lords", wiki: "Valley_of_the_Dark_Lords", sfq: "star wars korriban sith tomb valley" } ],
  taris: [ { name: "Taris Upper City", wiki: "Upper_City", sfq: "star wars taris kotor city" } ],
  dantooine: [ { name: "Jedi Enclave", wiki: "Jedi_Enclave", sfq: "star wars dantooine jedi enclave" } ],
  malachor: [ { name: "Sith temple", wiki: "Malachor_Sith_Temple", sfq: "star wars malachor sith temple rebels" } ],
  dromundkaas: [ { name: "Kaas City", wiki: "Kaas_City", sfq: "star wars dromund kaas sith city" } ],
  tython: [ { name: "Jedi Temple of Tython", wiki: "Jedi_Temple_(Tython)", sfq: "star wars tython jedi temple swtor" } ],
  bracca: [ { name: "Scrapper Guild yards", wiki: "Scrapper_Guild", sfq: "star wars bracca scrapyard fallen order" } ],
  bogano: [ { name: "Bogano vault", wiki: "Bogano_Vault", sfq: "star wars bogano vault fallen order" } ],
  zeffo: [ { name: "Tomb of Eilram", wiki: "Tomb_of_Eilram", sfq: "star wars zeffo tomb fallen order" } ],
  koboh: [ { name: "Rambler's Reach", wiki: "Rambler%27s_Reach_Outpost", sfq: "star wars koboh outpost jedi survivor" } ],
  nur: [ { name: "Fortress Inquisitorius", wiki: "Fortress_Inquisitorius", sfq: "star wars fortress inquisitorius" } ],
  ilum: [ { name: "Jedi Temple of Ilum", wiki: "Jedi_Temple_(Ilum)", sfq: "star wars ilum jedi temple crystal cave" } ],
  moncala: [ { name: "Mon Cala city", wiki: "Mon_Cala_City", sfq: "star wars mon cala underwater city" } ],
  cantonica: [ { name: "Canto Bight casino", wiki: "Canto_Casino_and_Racetrack", sfq: "star wars canto bight casino" } ],
  kijimi: [ { name: "Kijimi City", wiki: "Kijimi_City", sfq: "star wars kijimi city star wars" } ],
  kefbir: [ { name: "Death Star II wreck", wiki: "DS-2_Death_Star_II_Mobile_Battle_Station", sfq: "star wars death star wreck kef bir" } ],
  dqar: [ { name: "Resistance base", wiki: "Resistance_base_(D%27Qar)", sfq: "star wars resistance base d'qar" } ],
  hosnian: [ { name: "Republic City", wiki: "Republic_City", sfq: "star wars hosnian prime city" } ],
  starlight: [ { name: "Starlight Beacon", wiki: "Starlight_Beacon", sfq: "star wars starlight beacon high republic" } ],
  peridea: [ { name: "Nightsister fortress", wiki: "Great_Mothers%27_fortress", sfq: "star wars peridea fortress ahsoka" } ],
  seatos: [ { name: "Seatos henge", wiki: "Seatos_henge", sfq: "star wars seatos henge ahsoka" } ],
  polismassa: [ { name: "Polis Massa base", wiki: "Polis_Massa_Base", sfq: "star wars polis massa medical base" } ],
  ordmantell: [ { name: "Cid's Parlor", wiki: "Cid%27s_Parlor", sfq: "star wars cid parlor bad batch" } ],
  pabu: [ { name: "Pabu island", wiki: "Pabu", sfq: "star wars pabu island bad batch" } ],
  atattin: [ { name: "At Attin suburbs", wiki: "At_Attin", sfq: "star wars at attin skeleton crew" } ],
  hosnianx: [ { name: "The Colossus", wiki: "Colossus", sfq: "star wars colossus platform star wars resistance" } ],
  wayland: [ { name: "Mount Tantiss", wiki: "Mount_Tantiss", sfq: "star wars mount tantiss" } ],
  byss: [ { name: "Imperial Citadel", wiki: "Emperor%27s_Citadel", sfq: "star wars byss dark empire citadel" } ],
  serenno: [ { name: "Dooku's palace", wiki: "Dooku%27s_Palace", sfq: "star wars serenno dooku palace" } ],
  eriadu: [ { name: "Tarkin residence", wiki: "Tarkin_family_compound", sfq: "star wars eriadu tarkin" } ],
  batuu: [ { name: "Black Spire Outpost", wiki: "Black_Spire_Outpost", sfq: "star wars black spire outpost batuu" } ],
  vardos: [ { name: "Kestro", wiki: "Kestro", sfq: "star wars vardos kestro battlefront" } ],
  mimban: [ { name: "Mimban trenches", wiki: "Mimban_Campaign", sfq: "star wars mimban trench solo" } ],
  vandor: [ { name: "Fort Ypso", wiki: "Fort_Ypso", sfq: "star wars fort ypso vandor" } ],
  savareen: [ { name: "Savareen refinery", wiki: "Savareen_refinery", sfq: "star wars savareen refinery solo" } ],
  pasaana: [ { name: "Forbidden Valley", wiki: "Forbidden_Valley", sfq: "star wars pasaana festival star wars" } ],
  sorgan: [ { name: "Krill village", wiki: "Krill_farming_village", sfq: "star wars sorgan village mandalorian" } ],
  arvala7: [ { name: "Kuiil's homestead", wiki: "Kuiil%27s_homestead", sfq: "star wars arvala-7 mandalorian" } ],
  jabiim: [ { name: "Path hideout", wiki: "Jabiim_hideout", sfq: "star wars jabiim obi-wan kenobi" } ],
  daiyu: [ { name: "Daiyu city", wiki: "Daiyu", sfq: "star wars daiyu obi-wan kenobi city" } ],
  toshara: [ { name: "Mirogana", wiki: "Mirogana", sfq: "star wars mirogana outlaws" } ],
  telos: [ { name: "Citadel Station", wiki: "Citadel_Station", sfq: "star wars citadel station telos kotor" } ],
  manaan: [ { name: "Ahto City", wiki: "Ahto_City", sfq: "star wars ahto city manaan" } ],
  ossus: [ { name: "Great Jedi Library", wiki: "Great_Jedi_Library", sfq: "star wars ossus jedi library" } ],
  onderon: [ { name: "Iziz", wiki: "Iziz", sfq: "star wars iziz onderon city" } ],
  umbara: [ { name: "Umbaran capital", wiki: "Umbaran_capital", sfq: "star wars umbara clone wars" } ],
  mortis: [ { name: "Mortis monastery", wiki: "Monastery_(Mortis)", sfq: "star wars mortis monastery clone wars" } ],
  felucia: [ { name: "Felucia jungle", wiki: "Felucia", sfq: "star wars felucia force unleashed" } ],
  raxusprime: [ { name: "Raxus Prime junkfields", wiki: "Raxus_Prime", sfq: "star wars raxus prime junk" } ],
  akiva: [ { name: "Satrap's Palace", wiki: "Satrap%27s_Palace", sfq: "star wars akiva palace aftermath" } ],
  vrogasvas: [ { name: "Rebel refuelling base", wiki: "Vrogas_Vas", sfq: "star wars vrogas vas vader down" } ],
  shutorun: [ { name: "Ore-duke palace", wiki: "Shu-Torun", sfq: "star wars shu-torun darth vader comic" } ],
  carnelion: [ { name: "Carnelion IV ruins", wiki: "Carnelion_IV", sfq: "star wars carnelion iv obi-wan anakin" } ],
  kaller: [ { name: "Kaller battlefront", wiki: "Kaller", sfq: "star wars kaller bad batch order 66" } ],
  haruunkal: [ { name: "Pelek Baw", wiki: "Pelek_Baw", sfq: "star wars haruun kal shatterpoint" } ],
  hetzal: [ { name: "Hetzal Prime", wiki: "Hetzal_Prime", sfq: "star wars hetzal high republic" } ],
  ruusan: [ { name: "Valley of the Jedi", wiki: "Valley_of_the_Jedi", sfq: "star wars valley of the jedi ruusan" } ],
  myrkr: [ { name: "Hyllyard City", wiki: "Hyllyard_City", sfq: "star wars myrkr thrawn" } ],
  csilla: [ { name: "Csaplar", wiki: "Csaplar", sfq: "star wars csilla chiss city" } ],
  chandrila: [ { name: "Hanna City", wiki: "Hanna_City", sfq: "star wars hanna city chandrila" } ],
  ghorman: [ { name: "Palmo plaza", wiki: "Palmo", sfq: "star wars ghorman andor plaza" } ],
  brendok: [ { name: "Coven fortress", wiki: "Brendok_fortress", sfq: "star wars brendok acolyte" } ],
  shili: [ { name: "Corvala", wiki: "Corvala", sfq: "star wars shili togruta" } ],
  lahmu: [ { name: "Erso homestead", wiki: "Erso_homestead", sfq: "star wars lah'mu erso farm" } ],
  muunilinst: [ { name: "Harnaidan", wiki: "Harnaidan", sfq: "star wars muunilinst banking clan city" } ],
  apatros: [ { name: "Apatros mines", wiki: "Apatros", sfq: "star wars apatros cortosis mine" } ],
  nathema: [ { name: "Nathema ruins", wiki: "Nathema", sfq: "star wars nathema sith" } ],
  narshaddaa: [ { name: "Refugee Sector", wiki: "Refugee_Sector", sfq: "star wars nar shaddaa city" } ],
  alderaan: [ { name: "Aldera Royal Palace", wiki: "Royal_Palace_of_Alderaan", sfq: "star wars alderaan palace" } ],
};
